#! /usr/bin/env python

import os

from jinja2 import Environment, FileSystemLoader
env = Environment(loader=FileSystemLoader('templates'))

templates = ["hpfem.html", "uniquefeatures.html", "articles.html",
        "femcodes.html", "index.html", "development.html", "overview.html"]

out_dir = "output"
if not os.path.exists(out_dir):
    os.mkdir(out_dir)

os.system("cp default.css %s/" % out_dir)
os.system("cp -r images %s/" % out_dir)

for template in templates:
    t = env.get_template(template)
    open(os.path.join(out_dir, template), "w").write(t.render())
